/**
 * PDFBoogie end-to-end suite.
 *
 * Runs the *production build* (dist/, strict CSP) in headless Chromium and
 * exercises every tool with a variety of documents, images, drag & drop,
 * window resizing and list reordering. Outputs are downloaded through the
 * real browser download path and validated in Node (pdfjs / fflate / manual
 * binary checks).
 *
 * Fixtures: e2e/fixtures/*.pdf (generated by e2e/make-fixtures.mjs).
 * Images: generated in-page on <canvas> at exact dimensions.
 */
import { expect, type Locator, type Page, test } from '@playwright/test';
import {
  captureDownload,
  clickButton,
  docxText,
  docxXml,
  dropFiles,
  dropFixtures,
  firstZipEntry,
  fixtureBytes,
  formFieldValues,
  jpegSize,
  makeCanvasImages,
  odtXml,
  pdfImagePlacements,
  pdfInfo,
  pngSize,
  processAndDownload,
  webpSize,
  zipEntries,
} from './helpers';

/* ------------------------------------------------------------------ */
/* Small conveniences                                                  */
/* ------------------------------------------------------------------ */

const A4 = { w: 595, h: 842 }; // pt (± rounding from the 595.28/841.89 fixtures)

/** Expect no uncaught console errors or pageerrors on the page. */
function expectClean(page: Page) {
  const errors: string[] = [];
  page.on('pageerror', (e) => errors.push(String(e)));
  return () => {
    expect(errors, `uncaught errors: ${errors.join(' | ')}`).toHaveLength(0);
  };
}

/** Text of each file row (top to bottom). */
const rowNames = (page: Page) => page.locator('ul.filelist .file-row .file-name').allTextContents();

/** Wait until the file list has exactly `n` rows. */
async function expectRows(page: Page, n: number): Promise<void> {
  await expect(async () => {
    expect(await rowNames(page)).toHaveLength(n);
  }).toPass({ timeout: 15_000 });
}

/** Click move-up/down on row `i` (0-based). */
const moveRow = (page: Page, i: number, dir: 'up' | 'down') =>
  page
    .locator('ul.filelist .file-row')
    .nth(i)
    .locator('.file-actions button')
    .nth(dir === 'up' ? 0 : 1)
    .click();

const removeRow = (page: Page, i: number) =>
  page.locator('ul.filelist .file-row').nth(i).locator('.file-actions button').nth(2).click();

/** Assert no horizontal overflow at the current viewport. */
async function noHOverflow(page: Page) {
  const ok = await page.evaluate(
    () => Math.ceil(document.documentElement.scrollWidth) <= window.innerWidth + 1,
  );
  expect(ok, `horizontal overflow at ${await page.evaluate(() => window.innerWidth)}px`).toBe(true);
}

/* ------------------------------------------------------------------ */
/* 1. Site smoke — SSR content + responsive resizing                   */
/* ------------------------------------------------------------------ */

const ROUTES: Array<[string, RegExp]> = [
  ['/', /Free, secure/],
  ['/pdf-compress', /Compress PDF/],
  ['/pdf-merge', /Merge PDF/],
  ['/pdf-combine', /Combine pages/],
  ['/image-to-pdf', /Image to PDF/],
  ['/pdf-to-image', /PDF to [Ii]mage/],
  ['/pdf-to-doc', /PDF to Word/],
  ['/pdf-sign', /Sign/],
  ['/privacy', /Privacy/],
];

test.describe('site smoke', () => {
  for (const [path, h1] of ROUTES) {
    test(`${path} renders SSR h1, no horizontal overflow (1280)`, async ({ page }) => {
      const assertClean = expectClean(page);
      await page.goto(path);
      await expect(page.locator('h1').first()).toContainText(h1);
      await noHOverflow(page);
      // prerendered: content present without JS (meta title matches)
      await expect(page).toHaveTitle(/PDFBoogie|PDF/);
      assertClean();
    });

    test(`${path} holds layout at mobile (360) and tablet (768)`, async ({ page }) => {
      await page.setViewportSize({ width: 360, height: 740 });
      await page.goto(path);
      await expect(page.locator('h1').first()).toContainText(h1);
      await noHOverflow(page);

      await page.setViewportSize({ width: 768, height: 1024 });
      await page.waitForTimeout(150);
      await noHOverflow(page);
    });
  }

  test('unknown path returns 404; the prerendered 404 artifact renders', async ({ page }) => {
    const res = await page.goto('/definitely-not-a-page');
    expect(res?.status()).toBe(404);
    // A static server answers with its own 404; GitHub Pages is configured to serve
    // our prerendered 404.html for unknown paths — verify that artifact renders.
    await page.goto('/404.html');
    await expect(page.locator('h1')).toContainText(/404/);
  });

  test('static assets & SEO files are served', async ({ page }) => {
    for (const p of [
      '/sitemap.xml',
      '/robots.txt',
      '/og.png',
      '/favicon.svg',
      '/manifest.webmanifest',
      '/wasm/pdfcore_bg.wasm',
    ]) {
      const res = await page.request.get(p);
      expect(res.status(), `${p} → ${res.status()}`).toBe(200);
    }
    const sitemap = await page.request.get('/sitemap.xml');
    const body = await sitemap.text();
    expect(body).toContain('/pdf-to-doc');
  });

  test('ad slot: hidden until first op, then pixel-art thank-you placeholder (ad-free build)', async ({
    page,
  }) => {
    // The placeholder asset ships (local file, no external requests).
    expect((await page.request.get('/thank-you.gif')).status()).toBe(200);

    await page.goto('/pdf-compress');
    const slot = page.locator('.ad-slot[data-ad-slot="tool-bottom"]');
    // Idle: the slot is present but collapsed (zero footprint).
    await expect(slot).toHaveAttribute('data-expanded', 'false');

    await dropFixtures(page, ['text-5p.pdf']);
    await processAndDownload(page, /Compress \(lossless\)/);

    // First operation done: the slot expands and shows the pixel-art
    // placeholder (no AdSense client id in this build).
    await expect(slot).toHaveAttribute('data-expanded', 'true');
    const thanks = slot.locator('img.ad-thanks');
    await expect(thanks).toBeVisible();
    expect(await thanks.getAttribute('src')).toMatch(/thank-you\.gif$/);
    // No AdSense network request may have been made.
    expect(await thanks.getAttribute('alt')).toBe('Thank you for using PDFBoogie');
  });
});

/* ------------------------------------------------------------------ */
/* 2. DropZone — drag & drop behaviour (merge page as reference)       */
/* ------------------------------------------------------------------ */

test.describe('dropzone & drag/drop', () => {
  test('dragenter sets the dragging state; drop clears it', async ({ page }) => {
    await page.goto('/pdf-merge');
    const dz = page.locator('.dropzone');
    expect(await dz.getAttribute('data-dragging')).not.toBe('true');

    await page.evaluate(() => {
      const el = document.querySelector('.dropzone')!;
      const dt = new DataTransfer();
      el.dispatchEvent(
        new DragEvent('dragenter', { bubbles: true, cancelable: true, dataTransfer: dt }),
      );
      el.dispatchEvent(
        new DragEvent('dragover', { bubbles: true, cancelable: true, dataTransfer: dt }),
      );
    });
    await expect(dz).toHaveAttribute('data-dragging', 'true');

    await page.evaluate(() => {
      const el = document.querySelector('.dropzone')!;
      el.dispatchEvent(new DragEvent('dragleave', { bubbles: true, cancelable: true }));
    });
    await expect(dz).toHaveAttribute('data-dragging', 'false');
  });

  test('drop one PDF → one row; drop a second batch appends (order kept)', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-1p.pdf']);
    await expectRows(page, 1);
    expect(await rowNames(page)).toEqual(['text-1p.pdf']);

    await dropFixtures(page, ['text-5p.pdf', 'landscape-1p.pdf']);
    await expectRows(page, 3);
    expect(await rowNames(page)).toEqual(['text-1p.pdf', 'text-5p.pdf', 'landscape-1p.pdf']);
    assertClean();
  });

  test('dropping a non-PDF is rejected with a friendly error', async ({ page }) => {
    await page.goto('/pdf-merge');
    await dropFiles(page, [{ name: 'notes.txt', type: 'text/plain', data: [110, 105] }]);
    await expect(page.locator('.error-card')).toContainText('Not PDF or images: notes.txt');
    await expectRows(page, 0);
  });

  test('native <input type=file> path registers files', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await page
      .locator('.dz-input')
      .first()
      .setInputFiles([
        {
          name: 'text-1p.pdf',
          mimeType: 'application/pdf',
          buffer: Buffer.from(fixtureBytes('text-1p.pdf')),
        },
        {
          name: 'text-5p.pdf',
          mimeType: 'application/pdf',
          buffer: Buffer.from(fixtureBytes('text-5p.pdf')),
        },
      ]);
    await expectRows(page, 2);
    expect(await rowNames(page)).toEqual(['text-1p.pdf', 'text-5p.pdf']);
    assertClean();
  });

  test('dropzone tap target covers the zone (mobile-safe)', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 700 });
    await page.goto('/pdf-merge');
    const hit = await page.evaluate(() => {
      const dz = document.querySelector('.dropzone') as HTMLElement;
      const r = dz.getBoundingClientRect();
      const el = document.elementFromPoint(r.left + r.width / 2, r.top + r.height / 2);
      const input = document.querySelector('.dropzone input[type=file]') as HTMLElement | null;
      return el === input || (el !== null && input?.contains(el as Node));
    });
    expect(hit).toBe(true);
  });
});

/* ------------------------------------------------------------------ */
/* 3. Ordering — merge list reorder / remove + merge respects order    */
/* ------------------------------------------------------------------ */

test.describe('ordering (merge)', () => {
  test('up/down/remove controls reorder and prune the list', async ({ page }) => {
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-1p.pdf', 'text-5p.pdf', 'landscape-1p.pdf']);
    await expectRows(page, 3);

    // move first down → [5p, 1p, landscape]
    await moveRow(page, 0, 'down');
    expect(await rowNames(page)).toEqual(['text-5p.pdf', 'text-1p.pdf', 'landscape-1p.pdf']);
    // move last up → [5p, landscape, 1p]
    await moveRow(page, 2, 'up');
    expect(await rowNames(page)).toEqual(['text-5p.pdf', 'landscape-1p.pdf', 'text-1p.pdf']);
    // remove middle → [5p, 1p]
    await removeRow(page, 1);
    await expectRows(page, 2);
    expect(await rowNames(page)).toEqual(['text-5p.pdf', 'text-1p.pdf']);
  });

  test('merged PDF page order matches the final list order (text markers)', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    // [1p, 5p, landscape] → move 1p to the end → [5p, landscape, 1p]
    await dropFixtures(page, ['text-1p.pdf', 'text-5p.pdf', 'landscape-1p.pdf']);
    await expectRows(page, 3);
    await moveRow(page, 0, 'down'); // 1p → index 1: [5p, 1p, landscape]
    await moveRow(page, 1, 'down'); // 1p → index 2: [5p, landscape, 1p]
    expect(await rowNames(page)).toEqual(['text-5p.pdf', 'landscape-1p.pdf', 'text-1p.pdf']);

    const pdf = await processAndDownload(page, /^Merge 7 pages into one PDF$/);
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(7); // 5 + 1 + 1
    const texts = info.pages.map((p) => p.text);
    // pages 1-5 from text-5p, page 6 landscape, page 7 text-1p
    expect(texts[0]!).toContain('MARK-P1');
    expect(texts[4]!).toContain('MARK-P5');
    expect(texts[5]!).toContain('MARK-LANDSCAPE');
    expect(texts[6]!).toContain('MARK-ONE');
    assertClean();
  });

  test('mixing images + PDF: images get the chosen page size, PDFs keep theirs', async ({
    page,
  }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await makeCanvasImages(page, [
      { name: 'img-a.jpg', mime: 'image/jpeg', w: 600, h: 400, paint: 'hgrad' },
      { name: 'img-b.png', mime: 'image/png', w: 400, h: 600, paint: 'vgrad' },
    ]);
    await dropFixtures(page, ['text-1p.pdf']);
    await expectRows(page, 3);
    await page.selectOption('#mergePageSize', 'a4');

    const pdf = await processAndDownload(page, /^Merge 3 pages into one PDF$/);
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(3);
    const near = (a: number, b: number, tol = 2) => Math.abs(a - b) <= tol;
    // both image pages are A4 portrait; the PDF page keeps A4 too (fixture is A4)
    for (const pg of info.pages) {
      expect(near(pg.w, A4.w) && near(pg.h, A4.h), `page ${pg.w}×${pg.h}`).toBe(true);
    }
    assertClean();
  });

  test('encrypted PDF in merge → flagged on the row, merge disabled, no download', async ({
    page,
  }) => {
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-1p.pdf', 'encrypted.pdf']);
    await expectRows(page, 2);
    await expect(page.locator('.file-warn').first()).toContainText(/password|protected/i);
    await expect(page.locator('button.btn-primary')).toBeDisabled();
    await expect(page.locator('.result-card')).toHaveCount(0);
  });

  test('page strip renders every page as a thumbnail; CTA counts pages', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-5p.pdf', 'text-1p.pdf']);
    await expect(page.locator('.seq-tile')).toHaveCount(6);
    const thumbs = page.locator('.seq-tile img.seq-thumb');
    await expect(thumbs).toHaveCount(6);
    await imgRendered(thumbs.first());
    await expect(page.getByRole('button', { name: 'Merge 6 pages into one PDF' })).toBeEnabled();
    assertClean();
  });

  test('page-level reorder (arrows) changes the merged page order', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-5p.pdf', 'text-1p.pdf']);
    await expect(page.locator('.seq-tile')).toHaveCount(6);

    // move page 3 of text-5p to the front (two slots left)
    const left = page.getByRole('button', { name: 'Move page 3 of text-5p.pdf left' });
    await left.click();
    await left.click();

    const pdf = await processAndDownload(page, /^Merge 6 pages into one PDF$/);
    const texts = (await pdfInfo(pdf)).pages.map((p) => p.text);
    expect(texts.map((t) => /MARK-(P\d|ONE)/.exec(t)![1])).toEqual([
      'P3',
      'P1',
      'P2',
      'P4',
      'P5',
      'ONE',
    ]);
    assertClean();
  });

  test('pointer drag (grip) reorders the strip', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    // [1p, 5p×5] → drag the first tile's grip onto the last tile
    await dropFixtures(page, ['text-1p.pdf', 'text-5p.pdf']);
    const tiles = page.locator('.seq-tile');
    await expect(tiles).toHaveCount(6);
    // the loading tile (if any) shifts the layout when it goes away — wait it out
    await expect(page.locator('.seq-tile-loading')).toHaveCount(0);
    const grip = tiles.first().locator('.seq-grip');
    const last = tiles.last();
    const g = (await grip.boundingBox())!;
    const t = (await last.boundingBox())!;
    await page.mouse.move(g.x + g.width / 2, g.y + g.height / 2);
    await page.mouse.down();
    await page.mouse.move(t.x + t.width / 2, t.y + t.height / 2, { steps: 12 });
    await page.mouse.up();

    // 1p now sits before the last tile
    const ids = await tiles.evaluateAll((els) => els.map((e) => e.dataset.seqId!));
    expect(ids[4]!.endsWith('::1')).toBe(true);

    const pdf = await processAndDownload(page, /^Merge 6 pages into one PDF$/);
    const texts = (await pdfInfo(pdf)).pages.map((p) => p.text);
    expect(texts[4]!).toContain('MARK-ONE');
    expect(texts[5]!).toContain('MARK-P5');
    assertClean();
  });

  test('tap multi-select: the selection drags as a block', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-1p.pdf', 'text-5p.pdf']);
    const tiles = page.locator('.seq-tile');
    await expect(tiles).toHaveCount(6);
    await expect(page.locator('.seq-tile-loading')).toHaveCount(0);

    // tap tile bodies to select 1p + 5p/p1
    await tiles.nth(0).click();
    await tiles.nth(1).click();
    await expect(page.locator('.seq-tile.is-selected')).toHaveCount(2);
    await expect(page.locator('.seq-clear')).toContainText('2 selected');

    // drag the second selected tile's grip onto the last tile →
    // both selected pages land before it (in sequence order)
    const grip = tiles.nth(1).locator('.seq-grip');
    const last = tiles.last();
    const g = (await grip.boundingBox())!;
    const t = (await last.boundingBox())!;
    await page.mouse.move(g.x + g.width / 2, g.y + g.height / 2);
    await page.mouse.down();
    await page.mouse.move(t.x + t.width / 2, t.y + t.height / 2, { steps: 12 });
    await page.mouse.up();

    const pdf = await processAndDownload(page, /^Merge 6 pages into one PDF$/);
    const texts = (await pdfInfo(pdf)).pages.map((p) => p.text);
    expect(texts[3]!).toContain('MARK-ONE');
    expect(texts[4]!).toContain('MARK-P1');
    expect(texts[5]!).toContain('MARK-P5');
    assertClean();
  });

  test('selection arrows nudge the selected block one slot', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-5p.pdf', 'text-1p.pdf']);
    const tiles = page.locator('.seq-tile');
    await expect(tiles).toHaveCount(6);

    // select P1 + P2 (tiles 0, 1), nudge right → P3 slips in before them
    await tiles.nth(0).click();
    await tiles.nth(1).click();
    await page.getByRole('button', { name: 'Move page 1 of text-5p.pdf right' }).click();

    const pdf = await processAndDownload(page, /^Merge 6 pages into one PDF$/);
    const texts = (await pdfInfo(pdf)).pages.map((p) => p.text);
    expect(texts[0]!).toContain('MARK-P3');
    expect(texts[1]!).toContain('MARK-P1');
    expect(texts[2]!).toContain('MARK-P2');
    expect(texts[3]!).toContain('MARK-P4');
    assertClean();
  });

  test('ctrl+click adds to selection, shift+click selects a range', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-5p.pdf']);
    const tiles = page.locator('.seq-tile');
    await expect(tiles).toHaveCount(5);

    await tiles.nth(0).click(); // P1 selected
    await expect(page.locator('.seq-tile.is-selected')).toHaveCount(1);

    await tiles.nth(2).click({ modifiers: ['Control'] }); // add P3, keep P1
    await expect(page.locator('.seq-tile.is-selected')).toHaveCount(2);
    await expect(tiles.nth(1)).not.toHaveClass(/is-selected/);

    await tiles.nth(4).click({ modifiers: ['Shift'] }); // range P3..P5 (P1 stays)
    await expect(page.locator('.seq-tile.is-selected')).toHaveCount(4);

    // plain click on an unselected tile adds it without clearing the rest
    await tiles.nth(0).click({ modifiers: ['Control'] }); // deselect P1
    await expect(page.locator('.seq-tile.is-selected')).toHaveCount(3);

    // clear via the header chip
    await page.locator('.seq-clear').click();
    await expect(page.locator('.seq-tile.is-selected')).toHaveCount(0);
    assertClean();
  });

  test('image preview reflects page size and margins', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await makeCanvasImages(page, [
      { name: 'pic.png', mime: 'image/png', w: 800, h: 600, paint: 'hgrad' },
    ]);
    await expect(page.locator('.seq-tile')).toHaveCount(1);

    // Image pages now preview as a CSS page frame (shared geometry with the
    // real PDF writer): the frame box is the output page size at a fixed
    // tile scale, the image letterboxes inside it via object-fit, and the
    // margin insets the frame's content. No canvas re-renders per change.
    const frame = page.locator('.seq-image-page');
    const img = frame.locator('img');
    await expect(img).toBeVisible();
    const styleOf = () => frame.getAttribute('style');
    const fitStyle = (await styleOf())!;
    expect(fitStyle).toMatch(/width:/);
    expect(fitStyle).toMatch(/height:/);
    const fitBox = (await frame.boundingBox())!;
    // A fitted landscape page is wider than it is tall.
    expect(fitBox.width).toBeGreaterThan(fitBox.height);

    // A4: portrait frame — taller than the fitted frame.
    await page.selectOption('#mergePageSize', 'a4');
    await expect.poll(styleOf).not.toBe(fitStyle);
    const a4Style = (await styleOf())!;
    const a4Box = (await frame.boundingBox())!;
    expect(a4Box.height).toBeGreaterThan(fitBox.height);

    // Letter: different aspect → different frame.
    await page.selectOption('#mergePageSize', 'letter');
    await expect.poll(styleOf).not.toBe(a4Style);

    // Margins inset the image inside the frame; the page frame itself keeps
    // its size, only the inset changes.
    await page.selectOption('#mergePageSize', 'a4');
    const before = (await styleOf())!;
    expect(before).toMatch(/--preview-margin:\s*0px/);
    await page.selectOption('#mergeMargin', '24');
    await expect.poll(styleOf).not.toBe(before);
    expect((await styleOf())!).toMatch(/--preview-margin:\s*\d+px/);
    const afterBox = (await frame.boundingBox())!;
    expect(afterBox.height).toBeCloseTo(a4Box.height, 0);
    assertClean();
  });

  test('touch drag on the grip reorders (CDP touch, Android-style)', async ({ browser }) => {
    // A touch-enabled context: Chromium emits pointer events from these.
    const ctx = await browser.newContext({ hasTouch: true, viewport: { width: 390, height: 844 } });
    const tp = await ctx.newPage();
    await tp.goto('/pdf-merge');
    await dropFixtures(tp, ['text-1p.pdf', 'text-5p.pdf']);
    const tiles = tp.locator('.seq-tile');
    await expect(tiles).toHaveCount(6);
    await expect(tp.locator('.seq-tile-loading')).toHaveCount(0);
    await tp.evaluate(() =>
      document.querySelector('.seq-wrap')?.scrollIntoView({ block: 'center' }),
    );
    await tp.waitForTimeout(250);

    const grip = tiles.first().locator('.seq-grip');
    const target = tiles.nth(2); // tile 3 (P3) — inside the 390px viewport
    const g = (await grip.boundingBox())!;
    const t = (await target.boundingBox())!;
    const cdp = await ctx.newCDPSession(tp);
    const cx = g.x + g.width / 2;
    const cy = g.y + g.height / 2;
    const tx = t.x + t.width / 2;
    const ty = t.y + t.height / 2;
    await cdp.send('Input.dispatchTouchEvent', {
      type: 'touchStart',
      touchPoints: [{ x: cx, y: cy }],
    });
    for (let i = 1; i <= 10; i += 1) {
      await cdp.send('Input.dispatchTouchEvent', {
        type: 'touchMove',
        touchPoints: [{ x: cx + ((tx - cx) * i) / 10, y: cy + ((ty - cy) * i) / 10 }],
      });
    }
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    await tp.waitForTimeout(400);

    // 1p was inserted before P3
    const ids = await tiles.evaluateAll((els) => els.map((e) => e.dataset.seqId!));
    expect(ids[2]!.endsWith('::1')).toBe(true);
    await ctx.close();
  });
});

/* ------------------------------------------------------------------ */
/* 4. Combine (n-up)                                                    */
/* ------------------------------------------------------------------ */

test.describe('combine pages (n-up)', () => {
  test('page tiles render; selecting 2,4,5 at 2-up → 2 sheets', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-combine');
    await dropFixtures(page, ['text-5p.pdf']);
    await expect(page.locator('.page-tile')).toHaveCount(5, { timeout: 30_000 });
    // default = all selected
    expect(await page.locator('.page-tile[aria-pressed="true"]').count()).toBe(5);

    // unselect all, then pick 2, 4, 5
    await clickButton(page, /^None$/);
    expect(await page.locator('.page-tile[aria-pressed="true"]').count()).toBe(0);
    await page.locator('.page-tile', { hasText: /^2$/ }).click();
    await page.locator('.page-tile', { hasText: /^4$/ }).click();
    await page.locator('.page-tile', { hasText: /^5$/ }).click();
    expect(await page.locator('.page-tile[aria-pressed="true"]').count()).toBe(3);

    await page.selectOption('#grid', '2');
    const pdf = await processAndDownload(page, /^Combine 3 pages$/);
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(2); // ceil(3/2)
    expect(Math.round(info.pages[0]!.w)).toBeCloseTo(A4.w, -1);
    assertClean();
  });

  test('all 5 pages: 4-up → 2 sheets; 16-up → 1 sheet', async ({ page }) => {
    await page.goto('/pdf-combine');
    await dropFixtures(page, ['text-5p.pdf']);
    await page.selectOption('#grid', '4');
    const pdf = await processAndDownload(page, /^Combine 5 pages$/);
    expect((await pdfInfo(pdf)).pages).toHaveLength(2); // ceil(5/4)

    // restart with the same file, switch grid, recombine
    await clickButton(page, /Adjust and combine again/);
    await page.selectOption('#grid', '16');
    const pdf2 = await processAndDownload(page, /^Combine 5 pages$/);
    expect((await pdfInfo(pdf2)).pages).toHaveLength(1); // ceil(5/16)
  });

  test('9-up landscape sheet: output page is landscape A4', async ({ page }) => {
    await page.goto('/pdf-combine');
    await dropFixtures(page, ['text-5p.pdf']);
    await page.selectOption('#grid', '9');
    await page.selectOption('#sheetSize', 'a4');
    await page.selectOption('#orientation', 'landscape');
    const pdf = await processAndDownload(page, /^Combine 5 pages$/);
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(1);
    expect(info.pages[0]!.w).toBeGreaterThan(info.pages[0]!.h);
    expect(Math.round((info.pages[0]!.w / 842) * 10)).toBe(10); // ~842pt wide
  });

  test('page tiles show rendered thumbnails of the real pages', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-combine');
    await dropFixtures(page, ['text-5p.pdf']);
    await expect(page.locator('.page-tile')).toHaveCount(5, { timeout: 30_000 });
    await expect(page.locator('.page-tile img.page-tile-img')).toHaveCount(5, { timeout: 30_000 });
    await imgRendered(page.locator('.page-tile img.page-tile-img').first());
    assertClean();
  });

  test('None selected → combine button disabled', async ({ page }) => {
    await page.goto('/pdf-combine');
    await dropFixtures(page, ['text-5p.pdf']);
    await clickButton(page, /^None$/);
    await expect(page.locator('button', { hasText: /Combine selected/ })).toBeDisabled();
  });
});

/* ------------------------------------------------------------------ */
/* 5. Image → PDF                                                      */
/* ------------------------------------------------------------------ */

test.describe('image to PDF', () => {
  test('4 canvas images → 4 pages; fit pages match image aspect (pt = px×0.75)', async ({
    page,
  }) => {
    const assertClean = expectClean(page);
    await page.goto('/image-to-pdf');
    await makeCanvasImages(page, [
      { name: 'a.png', mime: 'image/png', w: 800, h: 600, paint: 'solid', color: [200, 60, 60] },
      { name: 'b.png', mime: 'image/png', w: 600, h: 800, paint: 'solid', color: [60, 120, 200] },
      { name: 'c.png', mime: 'image/png', w: 1000, h: 400, paint: 'quarters' },
      { name: 'd.png', mime: 'image/png', w: 256, h: 256, paint: 'solid', color: [60, 180, 90] },
    ]);
    await expectRows(page, 4);

    const pdf = await processAndDownload(page, /^Combine 4 images into a PDF$/);
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(4);
    const near = (a: number, b: number, tol = 2) => Math.abs(a - b) <= tol;
    expect(near(info.pages[0]!.w, 600) && near(info.pages[0]!.h, 450)).toBe(true); // 800×600 px
    expect(near(info.pages[1]!.w, 450) && near(info.pages[1]!.h, 600)).toBe(true); // 600×800 px
    expect(near(info.pages[2]!.w, 750) && near(info.pages[2]!.h, 300)).toBe(true); // 1000×400 px
    expect(near(info.pages[3]!.w, 192) && near(info.pages[3]!.h, 192)).toBe(true); // 256×256 px
    assertClean();
  });

  test('reordering changes output page order', async ({ page }) => {
    await page.goto('/image-to-pdf');
    await makeCanvasImages(page, [
      { name: 'a.png', mime: 'image/png', w: 800, h: 400, paint: 'solid', color: [200, 60, 60] },
      { name: 'b.png', mime: 'image/png', w: 400, h: 800, paint: 'solid', color: [60, 120, 200] },
      { name: 'c.png', mime: 'image/png', w: 500, h: 500, paint: 'solid', color: [90, 90, 200] },
    ]);
    await expectRows(page, 3);
    // move last to front: [a,b,c] → [a,c,b] → [c,a,b]
    await moveRow(page, 2, 'up'); // c → index 1
    await moveRow(page, 1, 'up'); // c → index 0
    expect(await rowNames(page)).toEqual(['c.png', 'a.png', 'b.png']);

    const pdf = await processAndDownload(page, /^Combine 3 images into a PDF$/);
    const info = await pdfInfo(pdf);
    const near = (a: number, b: number, tol = 2) => Math.abs(a - b) <= tol;
    // first page now the 500×500 image → 375×375 pt
    expect(near(info.pages[0]!.w, 375) && near(info.pages[0]!.h, 375)).toBe(true);
    // second page the 800×400 image → 600×300 pt
    expect(near(info.pages[1]!.w, 600) && near(info.pages[1]!.h, 300)).toBe(true);
  });

  test('A4 page size normalizes every page', async ({ page }) => {
    await page.goto('/image-to-pdf');
    await makeCanvasImages(page, [
      { name: 'a.png', mime: 'image/png', w: 900, h: 300, paint: 'solid' },
      { name: 'b.png', mime: 'image/png', w: 300, h: 900, paint: 'solid', color: [0, 150, 150] },
    ]);
    await expectRows(page, 2);
    await page.selectOption('#pageSize', 'a4');
    const pdf = await processAndDownload(page, /^Combine 2 images into a PDF$/);
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(2);
    for (const pg of info.pages) {
      expect(Math.abs(pg.w - A4.w)).toBeLessThanOrEqual(2);
      expect(Math.abs(pg.h - A4.h)).toBeLessThanOrEqual(2);
    }
  });

  test('JPEG and WebP inputs both produce a valid multi-page PDF', async ({ page }) => {
    await page.goto('/image-to-pdf');
    await makeCanvasImages(page, [
      { name: 'a.jpg', mime: 'image/jpeg', w: 700, h: 500, paint: 'quarters' },
      { name: 'b.webp', mime: 'image/webp', w: 500, h: 700, paint: 'hgrad' },
    ]);
    await expectRows(page, 2);
    const pdf = await processAndDownload(page, /^Combine 2 images into a PDF$/);
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(2);
  });

  test('removing an image before convert drops its page', async ({ page }) => {
    await page.goto('/image-to-pdf');
    await makeCanvasImages(page, [
      { name: 'a.png', mime: 'image/png', w: 400, h: 300, paint: 'solid' },
      { name: 'b.png', mime: 'image/png', w: 300, h: 400, paint: 'solid', color: [200, 100, 0] },
    ]);
    await expectRows(page, 2);
    await removeRow(page, 0);
    await expectRows(page, 1);
    expect(await rowNames(page)).toEqual(['b.png']);
    const pdf = await processAndDownload(page, /^Combine 1 image into a PDF$/);
    expect((await pdfInfo(pdf)).pages).toHaveLength(1);
  });
});

/* ------------------------------------------------------------------ */
/* 6. PDF → Image                                                       */
/* ------------------------------------------------------------------ */

test.describe('PDF to image', () => {
  test('single page → PNG at 96 DPI with correct pixel size', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-to-image');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.selectOption('#fmt', 'png');
    await page.selectOption('#dpi', '96');
    const png = await processAndDownload(page, /Convert .* to PNG/);
    const size = pngSize(png);
    expect(size).not.toBeNull();
    // A4 595.28×841.89 pt at 96 dpi → 794×1123 px
    expect(Math.abs(size!.w - 794)).toBeLessThanOrEqual(2);
    expect(Math.abs(size!.h - 1123)).toBeLessThanOrEqual(2);
    assertClean();
  });

  test('page subset 2–4 → ZIP with 3 JPEG entries (150 DPI)', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-to-image');
    await dropFixtures(page, ['text-5p.pdf']);
    await page.selectOption('#fmt', 'jpeg');
    await page.selectOption('#dpi', '150');
    await page.locator('input[aria-label="First page"]').fill('2');
    await page.locator('input[aria-label="Last page"]').fill('4');
    const zipBytes = await processAndDownload(page, /Convert pages 2[\u2013-]4 \(3\) to JPEG/);
    const entries = zipEntries(zipBytes);
    const names = Object.keys(entries);
    expect(names).toHaveLength(3);
    for (const n of names) {
      expect(jpegSize(entries[n]!)).not.toBeNull();
    }
    // page 3 is the 400×400 pt square → near-square JPEG at 150dpi (≈833×833)
    const third = names.find((n) => /3/.test(n))!;
    const s = jpegSize(entries[third]!)!;
    expect(Math.abs(s.w - s.h)).toBeLessThanOrEqual(4);
    assertClean();
  });

  test('WebP output carries the RIFF/WEBP header', async ({ page }) => {
    await page.goto('/pdf-to-image');
    await dropFixtures(page, ['landscape-1p.pdf']);
    await page.selectOption('#fmt', 'webp');
    await page.selectOption('#dpi', '96');
    const webp = await processAndDownload(page, /Convert .* to WebP/);
    expect(webpSize(webp)).not.toBeNull();
  });

  test('300 DPI landscape page → width > height', async ({ page }) => {
    await page.goto('/pdf-to-image');
    await dropFixtures(page, ['landscape-1p.pdf']);
    await page.selectOption('#fmt', 'png');
    await page.selectOption('#dpi', '300');
    const png = await processAndDownload(page, /Convert .* to PNG/);
    const s = pngSize(png)!;
    expect(s.w).toBeGreaterThan(s.h);
    // 841.89pt at 300dpi ≈ 3508px
    expect(Math.abs(s.w - 3508)).toBeLessThanOrEqual(6);
  });
});

/* ------------------------------------------------------------------ */
/* 7. PDF → Word / ODT                                                 */
/* ------------------------------------------------------------------ */

test.describe('PDF to doc', () => {
  test('text-5p → docx: all markers, 4 page breaks, Heading1 detected', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-to-doc');
    await dropFixtures(page, ['text-5p.pdf']);
    const docx = await processAndDownload(page, /Convert to \.docx/);
    const text = docxText(docx);
    for (const m of ['MARK-P1', 'MARK-P2', 'MARK-P3', 'MARK-P4', 'MARK-P5']) {
      expect(text, `missing ${m}`).toContain(m);
    }
    const xml = docxXml(docx);
    const breaks = (xml.match(/w:br w:type="page"/g) ?? []).length;
    expect(breaks).toBe(4); // 5 pages → 4 breaks
    expect(xml).toContain('Heading1'); // 24pt "Title One"
    assertClean();
  });

  test('text-1p → odt: valid ODF, mimetype first + stored, text present', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-to-doc');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.selectOption('#docfmt', 'odt');
    const odt = await processAndDownload(page, /Convert to \.odt/);
    const first = firstZipEntry(odt);
    expect(first.name).toBe('mimetype');
    expect(first.method).toBe(0); // stored, per ODF
    const content = odtXml(odt, 'content.xml');
    expect(content).toContain('MARK-ONE');
    assertClean();
  });

  test('scan (no text layer) → 0 paragraphs, valid doc, no crash', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-to-doc');
    await dropFixtures(page, ['scan-2p.pdf']);
    await page.selectOption('#docfmt', 'odt');
    const odt = await processAndDownload(page, /Convert to \.odt/);
    // must be a valid archive with a content part (even if nearly empty)
    const content = odtXml(odt, 'content.xml');
    expect(content).toContain('office:text');
    // UI still shows a result (0 paragraphs) rather than an error card
    await expect(page.locator('.result-card')).toHaveCount(1);
    assertClean();
  });
});

/* ------------------------------------------------------------------ */
/* 8. Compress                                                         */
/* ------------------------------------------------------------------ */

test.describe('compress', () => {
  test('lossless: valid PDF, page count preserved (text-5p)', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['text-5p.pdf']);
    const pdf = await processAndDownload(page, /Compress \(lossless\)/);
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(5);
    assertClean();
  });

  test('lossless on image-heavy: 3 valid pages', async ({ page }) => {
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['image-heavy-3p.pdf']);
    const pdf = await processAndDownload(page, /Compress \(lossless\)/);
    expect((await pdfInfo(pdf)).pages).toHaveLength(3);
  });

  test('strong 96 DPI on image-heavy → smaller than input, 3 pages', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['image-heavy-3p.pdf']);
    const inputSize = await page.evaluate(async () =>
      (await fetch('/e2e/fixtures/image-heavy-3p.pdf')).arrayBuffer().then((b) => b.byteLength),
    );
    // enable strong mode
    await page.locator('label.toggle input[type=checkbox]').check();
    await page.selectOption('#cdpi', '96');
    const pdf = await processAndDownload(page, /Compress \(strong\)/);
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(3);
    expect(pdf.byteLength, 'strong output should shrink a raster-heavy PDF').toBeLessThan(
      inputSize,
    );
    assertClean();
  });

  test('encrypted PDF → friendly error, no crash', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['encrypted.pdf']);
    await clickButton(page, /Compress \(lossless\)/);
    await expect(page.locator('.error-card')).toBeVisible();
    assertClean();
  });

  test('auto-picks strong for an image-heavy PDF, with a reason note', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['image-heavy-3p.pdf']);
    const note = page.locator('.auto-note');
    await expect(note).toBeVisible();
    await expect(note).toContainText(/image-heavy/);
    await expect(page.locator('label.toggle input[type=checkbox]')).toBeChecked();
    assertClean();
  });

  test('auto-picks lossless for a text PDF; manual switch clears the note', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['text-5p.pdf']);
    const note = page.locator('.auto-note');
    await expect(note).toBeVisible();
    await expect(note).toContainText(/text\/?vector/);
    const box = page.locator('label.toggle input[type=checkbox]');
    await expect(box).not.toBeChecked();
    await box.check();
    await expect(note).toHaveCount(0);
    await expect(box).toBeChecked();
    assertClean();
  });

  test('page preview strip renders thumbnails of the first pages', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['text-5p.pdf']);
    await expect(page.locator('.thumb-strip img')).toHaveCount(5, { timeout: 30_000 });
    await imgRendered(page.locator('.thumb-strip img').first());
    assertClean();
  });

  test('quality slider + value do not overlap at 360px', async ({ page }) => {
    await page.setViewportSize({ width: 360, height: 740 });
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.locator('label.toggle input[type=checkbox]').check(); // show the slider row
    const row = page.locator('.range-row').first();
    const slider = row.locator('input[type=range]');
    const out = row.locator('output');
    const sBox = (await slider.boundingBox())!;
    const oBox = (await out.boundingBox())!;
    expect(oBox.x + oBox.width, 'value within viewport').toBeLessThanOrEqual(361);
    expect(oBox.x, 'value does not overlap the slider').toBeGreaterThanOrEqual(
      sBox.x + sBox.width - 2,
    );
  });
});

/* ------------------------------------------------------------------ */
/* 9. Sign & Fill                                                       */
/* ------------------------------------------------------------------ */

/**
 * Wait until a rendered <img> has a decoded bitmap (naturalWidth > 0).
 * The <img> can exist before its (data-URL) bitmap finishes decoding on a
 * slow runner, so a single naturalWidth read can race the decode.
 */
async function imgRendered(img: Locator): Promise<void> {
  await expect
    .poll(() => img.evaluate((el) => el.naturalWidth), {
      timeout: 15_000,
    })
    .toBeGreaterThan(0, 'thumbnail decoded (naturalWidth > 0)');
}

/**
 * Wait for the sign stage (page N) to attach before interacting with it.
 * The PDF may still be opening on a slow CI runner; calling `boundingBox()`
 * first returns null and crashes the test.
 */
async function signStage(page: Page, n = 1) {
  const stage = page.locator(`.stage[data-page="${n}"]`);
  await expect(stage).toBeAttached({ timeout: 30_000 });
  return stage;
}

test.describe('sign & fill', () => {
  test('form panel lists all four fields', async ({ page }) => {
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['form.pdf']);
    // the form scan is async — wait for the last field to appear
    await expect(page.locator('.field > span[title="country"]')).toBeVisible();
    const names = await page
      .locator('.field > span[title]')
      .evaluateAll((els) => els.map((e) => e.getAttribute('title')));
    expect(names).toEqual(expect.arrayContaining(['name', 'email', 'agree', 'country']));
  });

  test('fill text + checkbox + dropdown → apply → values persist in the PDF', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['form.pdf']);
    await expect(page.locator('.field:has(span[title="name"]) input')).toBeVisible();
    await page.locator('.field:has(span[title="name"]) input').fill('Ada Lovelace');
    await page.locator('.field:has(span[title="email"]) input').fill('ada@example.com');
    // custom toggle: the visible control is the knob (the input is visually
    // hidden but real, layered over the knob) — clicking the input is what
    // the toggle does for the user
    await page.locator('.field:has(span[title="agree"]) .toggle input[type="checkbox"]').click();
    await expect(
      page.locator('.field:has(span[title="agree"]) input[type=checkbox]'),
    ).toBeChecked();
    await page.locator('.field:has(span[title="country"]) select').selectOption('DE');
    await clickButton(page, /Apply form fill/);

    // form-only download is now allowed
    const pdf = await captureDownload(page, () => clickButton(page, /Download filled PDF/));
    const values = await formFieldValues(pdf);
    expect(values.name).toBe('Ada Lovelace');
    expect(values.email).toBe('ada@example.com');
    expect(values.agree).toBe(true);
    expect(String(values.country)).toBe('DE');
    assertClean();
  });

  test('drawn signature: draw → use → place on page → download a bigger valid PDF', async ({
    page,
  }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['text-1p.pdf']);
    // draw a zigzag on the signature pad
    const pad = page.locator('canvas.sig-pad');
    const box = (await pad.boundingBox())!;
    await page.mouse.move(box.x + 15, box.y + box.height / 2);
    await page.mouse.down();
    for (let i = 1; i <= 14; i += 1) {
      await page.mouse.move(box.x + 15 + i * 12, box.y + box.height / 2 + (i % 2 === 0 ? -14 : 14));
    }
    await page.mouse.up();
    await clickButton(page, /^Use this signature$/);
    await expect(page.locator('.sig-preview img')).toHaveCount(1);
    // placing mode starts automatically on "Use this signature"
    const stage = await signStage(page);
    // element-based click: Playwright scrolls the (tall) stage into view
    // first, so the placement lands inside the viewport.
    const sbox = (await stage.boundingBox())!;
    await stage.click({ position: { x: sbox.width / 2, y: sbox.height * 0.75 } });
    await expect(page.locator('.stamp')).toHaveCount(1);

    const inputSize = await page.evaluate(async () =>
      (await fetch('/e2e/fixtures/text-1p.pdf')).arrayBuffer().then((b) => b.byteLength),
    );
    const pdf = await captureDownload(page, () =>
      clickButton(page, /Download signed PDF \(1 stamp\)/),
    );
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(1);
    expect(pdf.byteLength).toBeGreaterThan(inputSize); // an image stamp was embedded
    assertClean();
  });

  test('typed signature → download a valid PDF', async ({ page }) => {
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.locator('[role=tab]', { hasText: 'Type' }).click();
    await page.getByPlaceholder(/Alex Rivera/).fill('Alex Rivera');
    await clickButton(page, /^Use this signature$/);
    await expect(page.locator('.sig-preview img')).toHaveCount(1);
    // placing mode starts automatically on "Use this signature"
    const stage = await signStage(page);
    // element-based click: Playwright scrolls the (tall) stage into view
    // first, so the placement lands inside the viewport.
    const sbox = (await stage.boundingBox())!;
    await stage.click({ position: { x: 80, y: sbox.height * 0.8 } });
    await expect(page.locator('.stamp')).toHaveCount(1);
    const pdf = await captureDownload(page, () =>
      clickButton(page, /Download signed PDF \(1 stamp\)/),
    );
    expect((await pdfInfo(pdf)).pages).toHaveLength(1);
  });

  test('signature upload tab: drop a PNG → preview appears', async ({ page }) => {
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.locator('[role=tab]', { hasText: 'Upload' }).click();
    // a second dropzone is now the upload one — target it specifically
    await page.evaluate(async () => {
      const c = document.createElement('canvas');
      c.width = 300;
      c.height = 100;
      const ctx = c.getContext('2d')!;
      ctx.strokeStyle = '#111';
      ctx.lineWidth = 6;
      ctx.beginPath();
      ctx.moveTo(10, 50);
      ctx.bezierCurveTo(80, 10, 150, 90, 290, 40);
      ctx.stroke();
      const blob = await new Promise<Blob | null>((r) => c.toBlob(r, 'image/png'));
      const dt = new DataTransfer();
      dt.items.add(new File([blob!], 'sig.png', { type: 'image/png' }));
      // the upload dropzone is the one inside the signature panel (last on page)
      const zones = document.querySelectorAll('.dropzone');
      const target = zones[zones.length - 1] as HTMLElement;
      target.dispatchEvent(
        new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: dt }),
      );
    });
    await expect(page.locator('.sig-preview img')).toHaveCount(1);
  });

  test('placed stamp: drag, resize, and remove', async ({ page }) => {
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.locator('[role=tab]', { hasText: 'Type' }).click();
    await page.getByPlaceholder(/Alex Rivera/).fill('Alex Rivera');
    await clickButton(page, /^Use this signature$/);
    const stage = await signStage(page);
    const sbox = (await stage.boundingBox())!;
    await stage.click({ position: { x: sbox.width / 2, y: sbox.height / 2 } });
    await expect(page.locator('.stamp')).toHaveCount(1);
    const stamp = page.locator('.stamp');
    // the page is taller than the viewport: bring the stamp to a centered,
    // fully visible spot before dragging (mouse events need viewport space)
    await stamp.evaluate((el) => el.scrollIntoView({ block: 'center' }));
    await page.waitForTimeout(50);
    const before = (await stamp.boundingBox())!;
    // drag the stamp 60px left and 30px up
    await page.mouse.move(before.x + before.width / 2, before.y + before.height / 2);
    await page.mouse.down();
    await page.mouse.move(before.x + before.width / 2 - 60, before.y + before.height / 2 - 30, {
      steps: 8,
    });
    await page.mouse.up();
    const after = (await stamp.boundingBox())!;
    expect(after.x).toBeCloseTo(before.x - 60, -1);
    expect(after.y).toBeCloseTo(before.y - 30, -1);
    // ending the drag must not drop a duplicate stamp at the release point
    await expect(stamp).toHaveCount(1);
    // resize with the corner handle: drag it 40px to the right
    const handle = page.locator('.stamp-resize');
    await expect(handle).toHaveCount(1);
    const hbox = (await handle.boundingBox())!;
    const wBefore = after.width;
    await page.mouse.move(hbox.x + hbox.width / 2, hbox.y + hbox.height / 2);
    await page.mouse.down();
    await page.mouse.move(hbox.x + hbox.width / 2 + 40, hbox.y + hbox.height / 2, { steps: 6 });
    await page.mouse.up();
    const wAfter = (await stamp.boundingBox())!.width;
    expect(wAfter).toBeGreaterThan(wBefore + 20);
    // releasing the resize handle must not drop a duplicate stamp
    await expect(stamp).toHaveCount(1);
    await page.getByRole('button', { name: 'Remove', exact: true }).click();
    await expect(stamp).toHaveCount(0);
  });

  test('remove button on the stamp removes the placed signature', async ({ page }) => {
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.locator('[role=tab]', { hasText: 'Type' }).click();
    await page.getByPlaceholder(/Alex Rivera/).fill('Alex Rivera');
    await clickButton(page, /^Use this signature$/);
    const stage = await signStage(page);
    const sbox = (await stage.boundingBox())!;
    await stage.click({ position: { x: sbox.width / 2, y: sbox.height * 0.75 } });
    const stamp = page.locator('.stamp');
    await expect(stamp).toHaveCount(1);
    await stamp.evaluate((el) => el.scrollIntoView({ block: 'center' }));
    // the placed stamp is selected, so its on-stamp remove control is shown
    const remove = page.locator('.stamp-remove');
    await expect(remove).toHaveCount(1);
    await remove.click();
    await expect(stamp).toHaveCount(0);
  });

  test('placed stamp drags with Android-style touch events', async ({ browser }) => {
    const ctx = await browser.newContext({ hasTouch: true, viewport: { width: 390, height: 844 } });
    const tp = await ctx.newPage();
    await tp.goto('/pdf-sign');
    await dropFixtures(tp, ['text-1p.pdf']);
    await tp.locator('[role=tab]', { hasText: 'Type' }).click();
    await tp.getByPlaceholder(/Alex Rivera/).fill('Alex Rivera');
    await clickButton(tp, /^Use this signature$/);
    const stage = await signStage(tp);
    await stage.click({ position: { x: 80, y: 200 } });
    const stamp = tp.locator('.stamp');
    await expect(stamp).toHaveCount(1);
    await stamp.evaluate((el) => el.scrollIntoView({ block: 'center' }));
    await tp.waitForTimeout(100);
    const before = (await stamp.boundingBox())!;
    const cx = before.x + before.width / 2;
    const cy = before.y + before.height / 2;
    const cdp = await ctx.newCDPSession(tp);
    await cdp.send('Input.dispatchTouchEvent', {
      type: 'touchStart',
      touchPoints: [{ x: cx, y: cy }],
    });
    for (let i = 1; i <= 8; i += 1) {
      await cdp.send('Input.dispatchTouchEvent', {
        type: 'touchMove',
        touchPoints: [{ x: cx + (40 * i) / 8, y: cy + (20 * i) / 8 }],
      });
    }
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    await tp.waitForTimeout(100);
    const after = (await stamp.boundingBox())!;
    expect(after.x).toBeGreaterThan(before.x + 25);
    expect(after.y).toBeGreaterThan(before.y + 10);
    await expect(stamp).toHaveCount(1); // ending the drag must not place another stamp
    await ctx.close();
  });

  test('stamp placed at the page edge is clamped fully inside the page', async ({ page }) => {
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.locator('[role=tab]', { hasText: 'Type' }).click();
    await page.getByPlaceholder(/Alex Rivera/).fill('Alex Rivera');
    await clickButton(page, /^Use this signature$/);
    const stage = await signStage(page);
    const sbox = (await stage.boundingBox())!;
    // click ~4px inside the bottom-right corner: the stamp must fit on the page
    await stage.click({ position: { x: sbox.width - 4, y: sbox.height - 4 } });
    const stamp = page.locator('.stamp');
    await expect(stamp).toHaveCount(1);
    const cbox = (await page.locator('.stage[data-page="1"] .stage-canvas').boundingBox())!;
    const tbox = (await stamp.boundingBox())!;
    expect(tbox.x).toBeGreaterThanOrEqual(cbox.x - 1);
    expect(tbox.y).toBeGreaterThanOrEqual(cbox.y - 1);
    expect(tbox.x + tbox.width).toBeLessThanOrEqual(cbox.x + cbox.width + 1);
    expect(tbox.y + tbox.height).toBeLessThanOrEqual(cbox.y + cbox.height + 1);
    const pdf = await captureDownload(page, () =>
      clickButton(page, /Download signed PDF \(1 stamp\)/),
    );
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(1);
    const placements = await pdfImagePlacements(pdf);
    expect(placements).toHaveLength(1);
    const placed = placements[0]!;
    const pageInfo = info.pages[0]!;
    // Preview coordinates use a top-left origin; PDF image transforms use
    // bottom-left. Compare the downloaded matrix with the preview box.
    const expectedX = ((tbox.x - cbox.x) / cbox.width) * pageInfo.w;
    const expectedTop = ((tbox.y - cbox.y) / cbox.height) * pageInfo.h;
    const expectedW = (tbox.width / cbox.width) * pageInfo.w;
    const expectedH = (tbox.height / cbox.height) * pageInfo.h;
    const expectedY = pageInfo.h - expectedTop - expectedH;
    expect(Math.abs(placed.x - expectedX)).toBeLessThan(4);
    expect(Math.abs(placed.y - expectedY)).toBeLessThan(4);
    expect(Math.abs(placed.width - expectedW)).toBeLessThan(4);
    expect(Math.abs(placed.height - expectedH)).toBeLessThan(4);
  });

  test('stamps stay anchored to the page when the window resizes', async ({ page }) => {
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.locator('[role=tab]', { hasText: 'Type' }).click();
    await page.getByPlaceholder(/Alex Rivera/).fill('Alex Rivera');
    await clickButton(page, /^Use this signature$/);
    const stage = await signStage(page);
    const sbox = (await stage.boundingBox())!;
    await stage.click({ position: { x: sbox.width / 2, y: sbox.height * 0.75 } });
    await expect(page.locator('.stamp')).toHaveCount(1);
    const rel = async () => {
      const t = (await page.locator('.stamp').boundingBox())!;
      const c = (await page.locator('.stage[data-page="1"] .stage-canvas').boundingBox())!;
      return { rx: (t.x - c.x) / c.width, ry: (t.y - c.y) / c.height };
    };
    const a = await rel();
    await page.setViewportSize({ width: 800, height: 900 });
    await page.waitForTimeout(150); // let the ResizeObserver fire
    const b = await rel();
    expect(Math.abs(a.rx - b.rx)).toBeLessThan(0.02);
    expect(Math.abs(a.ry - b.ry)).toBeLessThan(0.02);
  });

  test('encrypted PDF → friendly error', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['encrypted.pdf']);
    await expect(page.locator('.error-card')).toBeVisible();
    assertClean();
  });
});

/* ------------------------------------------------------------------ */
/* 10. Resizing mid-flow                                               */
/* ------------------------------------------------------------------ */

test.describe('resizing mid-flow', () => {
  test('merge at 1280 → drop 3 → resize 360 (layout intact, reorder works) → resize 768 → merge completes', async ({
    page,
  }) => {
    const assertClean = expectClean(page);
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-1p.pdf', 'text-5p.pdf', 'landscape-1p.pdf']);
    await expectRows(page, 3);
    await noHOverflow(page);

    // shrink to mobile
    await page.setViewportSize({ width: 360, height: 740 });
    await page.waitForTimeout(150);
    await noHOverflow(page);
    await expect(page.locator('ul.filelist .file-row')).toHaveCount(3);
    // reorder still works at mobile width
    await moveRow(page, 0, 'down');
    expect(await rowNames(page)).toEqual(['text-5p.pdf', 'text-1p.pdf', 'landscape-1p.pdf']);

    // back to tablet and finish the merge
    await page.setViewportSize({ width: 768, height: 1024 });
    await page.waitForTimeout(150);
    await noHOverflow(page);
    const pdf = await processAndDownload(page, /^Merge 7 pages into one PDF$/);
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(7);
    expect(info.pages[0]!.text).toContain('MARK-P1');
    assertClean();
  });
});

/* ------------------------------------------------------------------ */
/* 13. No auto-download + tool chaining + combine live preview         */
/* ------------------------------------------------------------------ */

test.describe('downloads are explicit', () => {
  test('processing never auto-downloads; the Download button does', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['text-1p.pdf']);
    // static state: the Related links are visible (chain not yet active)
    await expect(page.locator('.related a')).not.toHaveCount(0);
    const downloads: string[] = [];
    page.on('download', (d) => {
      downloads.push(d.suggestedFilename());
    });

    await clickButton(page, /Compress \(lossless\)/);
    await page.waitForSelector('.result-card');
    await page.waitForTimeout(1200); // an auto-download would have fired by now
    expect(downloads).toHaveLength(0);

    await clickButton(page, /^Download PDF$/);
    await page.waitForTimeout(800);
    expect(downloads).toHaveLength(1);
    expect(downloads[0]!).toMatch(/-compressed\.pdf$/);
    assertClean();
  });
});

test.describe('tool chaining', () => {
  test('merge → "Continue with Compress" preloads the merged PDF', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-1p.pdf', 'landscape-1p.pdf']);
    await expect(page.locator('.seq-tile')).toHaveCount(2);

    // merge, but do NOT download — chain instead
    await clickButton(page, /^Merge 2 pages into one PDF$/);
    await page.waitForSelector('.result-card');
    await page.locator('.chain-link', { hasText: 'Compress' }).click();
    await page.waitForURL('**/pdf-compress');

    // the merged file was picked up automatically
    await expect(page.locator('.chain-note')).toContainText('merged.pdf');
    await expect(page.locator('.file-row .file-name', { hasText: 'merged.pdf' })).toBeVisible();

    // and it's ready to process from there
    const pdf = await processAndDownload(page, /Compress \(lossless\)/);
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(2);
    assertClean();
  });
});

test.describe('combine live preview', () => {
  test('output preview auto-updates when the layout changes', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-combine');
    await dropFixtures(page, ['text-5p.pdf']);
    await expect(page.locator('.sheet-preview')).toBeVisible();

    // 5 pages @ 4-up → 2 sheets
    await expect(page.locator('.sheet-preview-count')).toContainText('2 sheets');
    await expect(page.locator('.sheet-prev-img')).toHaveCount(2);

    // switch to 2-up → 3 sheets (preview re-renders automatically)
    await page.selectOption('#grid', '2');
    await expect(page.locator('.sheet-preview-count')).toContainText('3 sheets');
    await expect(page.locator('.sheet-prev-img')).toHaveCount(3);

    // deselecting a page updates the preview too
    await page.locator('.page-tile[aria-pressed="true"]').last().click();
    await expect(page.locator('.sheet-preview-count')).toContainText('2 sheets');
    assertClean();
  });
});
